export const FETCH_USER = "FETCH_USER";
// GOOGLE MAPS
export const FETCH_GOOGLE_MAPS = "FETCH_GOOGLE_MAPS";
// EVENT TYPES
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const GET_EVENTS = "GET_EVENTS";
export const JOIN_EVENT = "JOIN_EVENT";
export const GET_USER_EVENTS = "GET_USER_EVENTS";
export const GET_CATEGORY_EVENTS = "GET_CATEGORY_EVENTS";
export const GET_EVENT_DETAILS = "GET_EVENT_DETAILS";
export const LEAVE_EVENT = "LEAVE_EVENT";
